### ISSUE TITLE
missing Scimitar problems

### ISSUE THREAD

**Issue by EpsilonHydroid10** [VoidSorc/Total-Tinkers#13]
I don't know if its just me downloading a lot of Tinkers construct mods/addons, but I noticed that the scimitar isn't appearing in my U.I. I checked many times, reconfigured some mods, and deleted some mods to try and get it to appear but, it isn't appearing. so I don't know if I have to do something else, so if you do have time, can you potentially fix this problem, but if you don't, I can wait.

**Comment by UvMidnight** [comment]
What do you mean by missing? Is the scimitar visually not appearing if you have it as an item? Does it not exist? If it does not exist, have you enabled the experimental module in total tinkers?

**Comment by EpsilonHydroid10** [comment]
its not appearing as an item, and the weirder thing is that I check the three other custom modpack's I made for myself and it has the scimitar. so I don't know if a mod/addon I have is preventing it from appearing or not.

**Comment by UvMidnight** [comment]
I am going to look into it more. Send me a modlist of the pack that it is not appearing in

**Comment by EpsilonHydroid10** [comment]
the modpack is a custom I made solely for experimentation on various tinker's Construct parts. (im also using curseforge to download mods)

![Screenshot (593)](https://user-images.githubusercontent.com/62844745/77864796-69d6dc80-71f0-11ea-9d4d-78e0abc8fa05.png)

![Screenshot (592)](https://user-images.githubusercontent.com/62844745/77864795-69d6dc80-71f0-11ea-9d47-091911db2be1.png)

![Screenshot (591)](https://user-images.githubusercontent.com/62844745/77864794-69d6dc80-71f0-11ea-9f58-4c430e59332a.png)

**Comment by UvMidnight** [comment]
Tried using that modlist and had no problems. Are you **sure** that you have both the experimental module and the scimitar enabled in the config? In older versions of total tinkers, the experimental module was enabled by default.

**Comment by EpsilonHydroid10** [comment]
apparently, I did what you said and apparently it didn't registered it the few times. but now I enabled it. sorry for bugging you about it though...
