### ISSUE TITLE
Javelin textures are misaligned in 1.12.2

### ISSUE THREAD

**Issue by Enderkitty9** [VoidSorc/Total-Tinkers#7]
You are probably quite busy already, but I did find a small issue with the javelin texture.
Normally the javelin looks excellent, but once a modifier is added it looks strange.
Ex:
![Javelin bug](https://user-images.githubusercontent.com/58281030/69774337-4ffe8d80-115b-11ea-9d2a-49d48861c01d.png)

The mod looks excellent so far, so keep up the good work! Sorry if this isn't a great issue thread, it is my first time doing stuff on git hub. Thanks.

random other bit- This isn't a bug but a random suggestion, but it would be neat if the bone tools like the dagger, greatblade, and javelin's tool rod matched the others (looked like a bone)

**Comment by UvMidnight** [comment]
I could make bone textures, but i'd need to make them for every single part - I'm not confident I can make them look decent. The overlay thing is just a general bug with tinkers and modifiers that overlay parts of the weapon irc, firey is a common occurence of this.
