### ISSUE TITLE
Scimitars bypass shields

### ISSUE THREAD

**Issue by UvMidnight** [VoidSorc/Total-Tinkers#9]
Things to test:

Does it bypass invulnerability?
Does it bypass it for mobs?

**Comment by SonicX8000** [comment]
I should've worded it better in the discord but anyway...

-----

Actual Damage Invulnerability isn't bypassed, would be VERY broken if that happened. What I meant is that if a mob has some form of immunity were they 'block' damage taken from X amount of hits... like with a 'Shielding' affix from the Champions Mob. It will sound like they're taking so many hits while taking no damage. Once you get through their 'Shielding'... you then deal damage to them which respects the immunity frames.

By bypass for mobs... do you mean if the mob were holding a shield? When attacking a mob that's holding a shield they tend to 'block' the hit meaning you deal 0 damage... but the bleed effect from the scimitar will still apply on them much like with the Poison/Wither effects.
